# This yaml is located in ./app-root
# refers to the app2 related flux2 kustomization manifets
# wrapping the HCs to install
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-app1-helmcharts-wrappers
  namespace: flux-system
spec:
  force: false
  interval: 1m30s
  path: ./app-helmcharts-wrappers
  targetNamespace: flux-app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-app1

