apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-app1-helmcharts-wrappers
spec:
  force: false
  interval: 1m30s
  path: ./app-helmcharts-wrappers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-app1

